export const Strings = {
  en: {
    // Tabs
    tab_home: "Home",
    tab_accounts: "Accounts",
    tab_debts: "Debts",
    tab_invest: "Invest",
    tab_transactions: "Transactions",
    tab_connections: "Connections",

    // Home (Overview)
    overview_title: "Overview",
    overview_subtitle: "Your financial dashboard",
    total_assets: "Total Assets",
    total_liabilities: "Total Liabilities",
    balances_hidden: "Balances hidden via Settings",
    pull_to_refresh: "Pull to refresh",
    statistics_title: "Statistics",
    income_label: "Income",
    expenses_label: "Expenses",
    uncategorized: "Uncategorized",
    total: "Total",
    average: "Avg",
    avg_per_month: "Avg / month",

    // Accounts
    accounts_title: "Accounts",
    accounts_subtitle: "Overview of your finances",
    net_worth: "Total Net Worth",
    bank_assets: "Bank Assets",
    cash_at_hand: "Cash at Hand",
    edit_cash: "EDIT",
    add_manual_account: "Add Manual Account",
    no_accounts: "No accounts yet",
    no_accounts_hint: "Add a manual account or connect a bank",
    update_cash_title: "Update Cash Balance",
    save: "Save",
    cancel: "Cancel",
    add_manual_title: "Add Manual Account",
    name_label: "Name",
    balance_label: "Initial Balance",
    category_label: "Category",
    create_btn: "Create",
    placeholder_name: "e.g. My Safe",
    cat_giro: "Giro",
    cat_savings: "Savings",
    cat_stock: "Stock",
    cat_ignore: "Ignore",
    system_category: "System category",
    system_category_delete_blocked: "System category — cannot be deleted.",

    // Debts
    debts_title: "Debts",
    total_net_position: "Total Net Position",
    manage_people: "Manage People",
    no_people: "No people or institutions added yet.",
    owes_me: "Owes me",
    i_owe: "I owe",
    settled: "Settled",
    add_person_alert_title: "No People",
    add_person_alert_msg: "Please add a person first.",
    add_person_btn: "Add Person",
    manage_people_title: "Manage People",
    new_person_name: "New Person Name",
    close: "Close",
    add_debt_title: "Add Debt",
    person_label: "Person",
    amount_label: "Amount",
    desc_label: "Description",
    placeholder_desc: "What for?",
    who_owes_who: "Who owes who?",
    i_owe_them: "I Owe Them",
    they_owe_me: "They Owe Me",
    net_balance: "Net Balance",
    history: "History",
    no_history: "No history.",

    // Invest
    invest_title: "ETF Savings Plan",
    save_current_profile: "+ Save Current",
    reset: "Reset ↺",
    initial_inv: "Initial Investment",
    initial_inv_sub: "One-time amount",
    monthly_inv: "Monthly Investment",
    monthly_inv_sub: "Regular amount",
    duration: "Duration",
    duration_sub: "Years to invest",
    est_return: "Est. Return",
    est_return_sub: "Annual average",
    total_value: "Total Value",
    total_invested: "Total Invested",
    total_gain: "Total Gain",
    graph_note: "Graph showing growth over {years} years.",
    edit_profile_title: "Edit Profile",
    save_profile_title: "Save Profile",
    profile_name_label: "Name",
    profile_color_label: "Color",
    delete_profile_title: "Delete Profile?",
    delete_profile_msg: "Delete {name}?",
    manage_profiles: "Manage Profiles",
    create_profile: "Create Profile",
    edit: "Edit",
    delete: "Delete",
    update: "Update",
    years_suffix: " Years",

    // Connections
    connections_title: "Connections",
    connections_subtitle: "Link your bank accounts via Open Banking",
    connect_bank_btn: "+ Connect Bank",
    connecting: "Connecting to your bank...",
    have_code_btn: "Have a code? Enter manually",
    manual_code_hint:
      "Browser didn't redirect back? Copy the 'code' from the URL bar and paste it here:",
    submit_code: "Submit Code",
    select_bank_title: "Select Bank",
    search_bank_placeholder: "Search bank...",
    remove: "Remove",
    connected_account_count: "{count} account(s) connected",
    connected_date: "Connected {date}",
    no_connections: "No bank accounts connected yet",
    ready_to_connect: "Ready to connect!",
    open_bank_login: "Open Bank Login",

    // Account Details
    transactions_title: "Transactions",
    date_range: "Date range",
    date_range_title: "DATE RANGE",
    filter_all: "All",
    filter_year: "This Year",
    filter_90: "90 Days",
    filter_30: "30 Days",
    filter_custom: "Custom",
    add_transaction: "+ Add Transaction",
    quick_add: "Quick add",
    auto_categorize: "Categorizing",
    ai_processing: "Categorizing...",
    delete_account: "Delete Account",
    delete_account_confirm:
      "Are you sure you want to delete this account? This action cannot be undone.",
    add_tx_title: "Add Transaction",
    edit_tx_title: "Edit Transaction",
    tx_title_label: "Title / Payee",
    tx_amount_label: "Amount (negative for expense)",
    change_category: "Change Category",
    manage_categories: "Manage Categories",
    ai_overload_title: "Service Busy",
    ai_overload_msg:
      "The categorization service is currently experiencing high demand. Please try again in a moment.",
    ai_categorization_title: "Categorization",
    ai_categorization_desc:
      "Which transactions would you like the service to process?",
    uncategorized_only: "Uncategorized Only",
    recategorize_all: "Recategorize All",

    // Settings
    settings_title: "Settings",
    appearance: "Appearance",
    appearance_sub: "Choose your theme preference",
    theme_system: "System Default",
    theme_light: "Light",
    theme_dark: "Dark",
    palette: "Color theme",
    palette_mulberry: "Mulberry",
    palette_red: "Red",
    palette_purple: "Purple",
    palette_green: "Green",
    palette_turquoise: "Turquoise",
    ai_integration: "Categorization Integration",
    gemini_api_key: "Gemini API Key",
    ai_section: "AI",
    ai_gemini_key_label: "Gemini API key",
    ai_gemini_explainer:
      "Required for Gemini-based categorization. Stored locally on your device.",
    ai_gemini_key_set: "Set API key",
    ai_gemini_key_update: "Update key",
    ai_gemini_key_save: "Save",
    not_set: "Not set",
    privacy: "Privacy",
    hide_total: "Hide Total Amount",
    hide_total_sub: "Hides all balances until deactivated with PIN.",
    change_pin: "Change PIN",
    set_privacy_pin: "Set Privacy PIN",
    update_pin_sub: "Update your 5-digit security PIN.",
    protect_balances_sub: "Protect your hidden balances.",
    enter_new_pin: "Enter New PIN",
    create_pin: "Create 5-Digit PIN",
    enter_current_pin: "Enter Current PIN",
    enter_pin: "Enter PIN",
    set_pin_btn: "Set PIN",
    confirm_btn: "Confirm",
    save_key_btn: "Save Key",
    language: "Language",
    language_sub: "Select your preferred language",
    english: "English",
    german: "German",
    dashboard_section: "Dashboard",
    main_account: "Main Account",
    main_account_sub: "Account used for the dashboard breakdown.",
    select_main_account: "Select Main Account",

    // Dashboard
    by_category: "By Category",
    net: "Net",

    // Account Details
    import: "Import",
    categories: "Categories",

    // Bank Statements
    stmt_title: "Statements",
    stmt_empty: "No statements imported yet",
    stmt_empty_hint: "Use the Import button to upload bank statements",
    stmt_delete_title: "Delete Statement",
    stmt_delete_msg: "Delete this statement and all imported transactions?",
    stmt_imported: "imported",
    stmt_skipped: "skipped",
    stmt_count_single: "statement",
    stmt_count_plural: "statements",
    stmt_open_pdf: "Open PDF",
    stmt_pdf_unavailable: "PDF not available for this statement",

    // Date Range Picker
    filter_by_date: "Filter by Date",
    from: "From",
    to: "To",
    apply: "Apply",

    // Debts
    they_owe_you: "They owe you",
    you_owe: "You owe",
    actions: "Actions",
    no_people_added: "No people added yet",
    add_btn: "+ Add",
    people_tracked: "{count} people tracked",
    person_tracked: "1 person tracked",

    // Invest
    growth_chart: "Growth chart",

    // Connections
    connect_bank: "Connect a bank",
    connected_accounts: "Connected accounts",

    // Branding
    app_title: "Finance Manager by Monte",
  },
  de: {
    // Tabs
    tab_home: "Übersicht",
    tab_accounts: "Konten",
    tab_debts: "Schulden",
    tab_invest: "Investieren",
    tab_transactions: "Transaktionen",
    tab_connections: "Verbinden",

    // Home (Overview)
    overview_title: "Übersicht",
    overview_subtitle: "Dein Finanz-Dashboard",
    total_assets: "Gesamtvermögen",
    total_liabilities: "Gesamtverbindlichkeiten",
    balances_hidden: "Guthaben ausgeblendet (Einstellungen)",
    pull_to_refresh: "Ziehen zum Aktualisieren",
    statistics_title: "Statistiken",
    income_label: "Einkommen",
    expenses_label: "Ausgaben",
    uncategorized: "Unkategorisiert",
    total: "Gesamt",
    average: "Ø",
    avg_per_month: "Ø / Monat",

    // Dashboard
    by_category: "Kategorie",
    net: "Netto",

    // Accounts
    accounts_title: "Konten",
    accounts_subtitle: "Übersicht deiner Finanzen",
    net_worth: "Gesamtnettovermögen",
    bank_assets: "Bankvermögen",
    cash_at_hand: "Bargeld",
    edit_cash: "BEARB.",
    add_manual_account: "Manuelles Konto",
    no_accounts: "Noch keine Konten",
    no_accounts_hint: "Füge ein manuelles Konto hinzu oder verbinde eine Bank",
    update_cash_title: "Bargeldbestand aktualisieren",
    save: "Speichern",
    cancel: "Abbrechen",
    add_manual_title: "Manuelles Konto hinzufügen",
    name_label: "Name",
    balance_label: "Anfangsbestand",
    category_label: "Kategorie",
    create_btn: "Erstellen",
    placeholder_name: "z.B. Mein Tresor",
    cat_giro: "Giro",
    cat_savings: "Spar",
    cat_stock: "Depot",
    cat_ignore: "Ignorieren",
    system_category: "Systemkategorie",
    system_category_delete_blocked:
      "Systemkategorie — kann nicht gelöscht werden.",

    // Debts
    debts_title: "Schulden",
    total_net_position: "Gesamtposition",
    manage_people: "Personen verwalten",
    no_people: "Noch keine Personen oder Institutionen.",
    owes_me: "Schuldet mir",
    i_owe: "Ich schulde",
    settled: "Ausgeglichen",
    add_person_alert_title: "Keine Personen",
    add_person_alert_msg: "Bitte füge zuerst eine Person hinzu.",
    add_person_btn: "Person hinzufügen",
    manage_people_title: "Personen verwalten",
    new_person_name: "Name der neuen Person",
    close: "Schließen",
    add_debt_title: "Schuld hinzufügen",
    person_label: "Person",
    amount_label: "Betrag",
    desc_label: "Beschreibung",
    placeholder_desc: "Wofür?",
    who_owes_who: "Wer schuldet wem?",
    i_owe_them: "Ich schulde",
    they_owe_me: "Schuldet mir",
    net_balance: "Nettosaldo",
    history: "Verlauf",
    no_history: "Kein Verlauf.",
    they_owe_you: "Schuldet mir",
    you_owe: "Ich schulde",
    actions: "Aktionen",
    no_people_added: "Noch keine Personen hinzugefügt",
    add_btn: "+ Hinzufügen",
    people_tracked: "{count} Personen verfolgt",
    person_tracked: "1 Person verfolgt",

    // Invest
    invest_title: "ETF Sparplan",
    save_current_profile: "+ Profil speichern",
    reset: "Zurücksetzen ↺",
    initial_inv: "Startkapital",
    initial_inv_sub: "Einmaliger Betrag",
    monthly_inv: "Monatliche Rate",
    monthly_inv_sub: "Regelmäßiger Betrag",
    duration: "Laufzeit",
    duration_sub: "Jahre",
    est_return: "Erwartete Rendite",
    est_return_sub: "Jährlicher Durchschnitt",
    total_value: "Gesamtwert",
    total_invested: "Investiert",
    total_gain: "Gewinn",
    graph_note: "Wachstum über {years} Jahre.",
    edit_profile_title: "Profil bearbeiten",
    save_profile_title: "Profil speichern",
    profile_name_label: "Name",
    profile_color_label: "Farbe",
    delete_profile_title: "Profil löschen?",
    delete_profile_msg: "{name} löschen?",
    manage_profiles: "Profile verwalten",
    create_profile: "Profil erstellen",
    edit: "Bearbeiten",
    delete: "Löschen",
    update: "Aktualisieren",
    years_suffix: " Jahre",
    growth_chart: "Wachstumschart",

    // Connections
    connections_title: "Verbindungen",
    connections_subtitle: "Bankkonten via Open Banking verbinden",
    connect_bank_btn: "+ Bank verbinden",
    connecting: "Verbinde mit Bank...",
    have_code_btn: "Hast du einen Code? Manuell eingeben",
    manual_code_hint:
      "Browser nicht zurückgekehrt? Kopiere den 'Code' aus der URL-Leiste:",
    submit_code: "Code senden",
    select_bank_title: "Bank auswählen",
    search_bank_placeholder: "Bank suchen...",
    remove: "Entfernen",
    connected_account_count: "{count} Konto/Konten verbunden",
    connected_date: "Verbunden am {date}",
    no_connections: "Noch keine Bankkonten verbunden",
    ready_to_connect: "Bereit zum Verbinden!",
    open_bank_login: "Bank-Login öffnen",
    connect_bank: "Bank verbinden",
    connected_accounts: "Verbundene Konten",

    // Account Details
    transactions_title: "Transaktionen",
    date_range: "Zeitraum",
    date_range_title: "ZEITRAUM",
    filter_all: "Gesamt",
    filter_year: "Dieses Jahr",
    filter_90: "90 Tage",
    filter_30: "30 Tage",
    filter_custom: "Benutzerdefiniert",
    add_transaction: "+ Transaktion",
    quick_add: "Schnellerfassung",
    auto_categorize: "Kategorisieren",
    ai_processing: "Kategorien werden zugewiesen...",
    delete_account: "Konto löschen",
    delete_account_confirm:
      "Möchtest du dieses Konto wirklich löschen? Dies kann nicht rückgängig gemacht werden.",
    add_tx_title: "Transaktion hinzufügen",
    edit_tx_title: "Transaktion bearbeiten",
    tx_title_label: "Titel / Empfänger",
    tx_amount_label: "Betrag (negativ für Ausgaben)",
    change_category: "Kategorie ändern",
    manage_categories: "Kategorien verwalten",
    ai_overload_title: "Dienst ausgelastet",
    ai_overload_msg:
      "Der Kategorisierungs-Dienst ist derzeit stark ausgelastet. Bitte versuche es in einem Moment erneut.",
    ai_categorization_title: "Kategorisierung",
    ai_categorization_desc: "Welche Transaktionen sollen verarbeitet werden?",
    uncategorized_only: "Nur Unkategorisierte",
    recategorize_all: "Alle neu kategorisieren",
    import: "Importieren",
    categories: "Kategorien",

    // Bank Statements
    stmt_title: "Kontoauszüge",
    stmt_empty: "Noch keine Kontoauszüge importiert",
    stmt_empty_hint:
      "Verwende die Import-Schaltfläche, um Kontoauszüge hochzuladen",
    stmt_delete_title: "Kontoauszug löschen",
    stmt_delete_msg: "Kontoauszug und alle importierten Transaktionen löschen?",
    stmt_imported: "importiert",
    stmt_skipped: "übersprungen",
    stmt_count_single: "Kontoauszug",
    stmt_count_plural: "Kontoauszüge",
    stmt_open_pdf: "PDF öffnen",
    stmt_pdf_unavailable: "Keine PDF für diesen Kontoauszug verfügbar",

    // Date Range Picker
    filter_by_date: "Nach Datum filtern",
    from: "Von",
    to: "Bis",
    apply: "Anwenden",

    // Settings
    settings_title: "Einstellungen",
    appearance: "Erscheinungsbild",
    appearance_sub: "Wähle dein bevorzugtes Design",
    theme_system: "Systemstandard",
    theme_light: "Hell",
    theme_dark: "Dunkel",
    palette: "Farbschema",
    palette_mulberry: "Mulberry",
    palette_red: "Rot",
    palette_purple: "Lila",
    palette_green: "Grün",
    palette_turquoise: "Türkis",
    ai_integration: "Kategorisierungs-Integration",
    gemini_api_key: "Gemini API-Schlüssel",
    ai_section: "KI",
    ai_gemini_key_label: "Gemini API-Schlüssel",
    ai_gemini_explainer:
      "Erforderlich für Gemini-Kategorisierung. Lokal auf deinem Gerät gespeichert.",
    ai_gemini_key_set: "Schlüssel speichern",
    ai_gemini_key_update: "Schlüssel ändern",
    ai_gemini_key_save: "Speichern",
    not_set: "Nicht gesetzt",
    privacy: "Privatsphäre",
    hide_total: "Gesamtbeträge ausblenden",
    hide_total_sub: "Versteckt alle Guthaben bis zur PIN-Eingabe.",
    change_pin: "PIN ändern",
    set_privacy_pin: "Privatsphäre-PIN setzen",
    update_pin_sub: "Ändere deine 5-stellige Sicherheits-PIN.",
    protect_balances_sub: "Schütze deine ausgeblendeten Guthaben.",
    enter_new_pin: "Neue PIN eingeben",
    create_pin: "5-stellige PIN erstellen",
    enter_current_pin: "Aktuelle PIN eingeben",
    enter_pin: "PIN eingeben",
    set_pin_btn: "PIN setzen",
    confirm_btn: "Bestätigen",
    save_key_btn: "Schlüssel speichern",
    language: "Sprache",
    language_sub: "Wähle deine bevorzugte Sprache",
    english: "Englisch",
    german: "Deutsch",
    dashboard_section: "Übersicht",
    main_account: "Hauptkonto",
    main_account_sub: "Konto, das für die Dashboard-Auswertung verwendet wird.",
    select_main_account: "Hauptkonto auswählen",

    // Branding
    app_title: "Finanzmanager von Monte",
  },
};
